# Generated by Django 5.0.6 on 2024-05-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
